version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: named-queries-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: named-queries
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - named-queries-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: named-queries-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/named-queries?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - named-queries-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: named-queries-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - named-queries-network

volumes:
  mongodb_data:

networks:
  named-queries-network:
    driver: bridge